### ISSUE TITLE
Home 페이지 만들기

### ISSUE THREAD

**Issue by yonaSeo** [yonaSeo/GAMAGU#2]
# 🛠️ Issue
Tab Bar 메뉴에서 Home 페이지에 해당하는 뷰를 만든다.
# ☑️ Tasks
- [ ] Header 만들기 (Navigation Bar 설정)
- [ ] Footer 만들기 (Tab Bar 설정)
- [ ] Segmented Control 설정
- [ ] Carousel (CollectionView + ScrollView) 만들기
- [ ] TableView 만들기
